version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing app dependencies...
      - apt-get update
      - apt-get install -y docker.io
      - if [ $(uname -m) = "aarch64" ]; then
          curl -LO https://dl.k8s.io/release/v1.27.1/bin/linux/arm64/kubectl;
        else
          curl -LO https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl;
        fi
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --client

  pre_build:
    commands:
      - set -e
      - set -x
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 908778560637.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker build -t patdada/amazon:v1.0.0 .

  post_build:
    commands:
      - printenv
      - echo Build completed on $(date)
      - echo Pushing the Docker image...
      - docker push patdada/amazon:v1.0.0
      - echo Push the latest image to cluster
      - kubectl apply -f deployment.yml
