version: 0.2

phases:
  install:
    commands:
      - echo Installing app dependencies...
      - if [ $(uname -m) = "aarch64" ]; then
          curl -LO https://dl.k8s.io/release/v1.27.1/bin/linux/arm64/kubectl;
        else
          curl -LO https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl;
        fi
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --client

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws_ecr_password=$(aws ecr get-login-password --region us-east-1)
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 908778560637.dkr.ecr.us-east-1.amazonaws.com
      - export IMAGE_REPO_NAME=patdada/nodejswebapp
      - export IMAGE_TAG=v1.0.0

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker login
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on $(date)
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Push the latest image to cluster
      - kubectl apply -f deployment.yml
