phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Using Docker 20"

  pre_build:
    commands:
      - set -e
      - set -x
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 908778560637.dkr.ecr.us-east-1.amazonaws.com
      - docker pull 908778560637.dkr.ecr.us-east-1.amazonaws.com/patdada/nodejs-webapp:latest || true  # Pull the existing image, ignore errors

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker buildx build --platform linux/amd64,linux/arm64 -t patdada/nodejs-webapp --push .
 
  post_build:
    commands:
      - printenv
      - echo Build completed on $(date)
      - echo Pushing the Docker image...
      - docker push patdada/nodejs-webapp:latest
      - echo Push the latest image to cluster
      - kubectl apply -f deployment.yml
