version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23  # Adjust the Docker version to a valid one
    commands:
      - echo "Using Docker 23"

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 908778560637.dkr.ecr.us-east-1.amazonaws.com
      - docker pull 908778560637.dkr.ecr.us-east-1.amazonaws.com/patdada/bella-docker:v1.0.0 || true

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker buildx build --platform linux/amd64,linux/arm64 -t patdada/bella-docker:v1.0.0 --push
      - docker tag patdada/bella-docker:v1.0.0 908778560637.dkr.ecr.us-east-1.amazonaws.com/patdada/docker-bella:v1.0.0
      - docker push 908778560637.dkr.ecr.us-east-1.amazonaws.com/patdada/bella-docker:v1.0.0

  post_build:
    commands:
      - echo Build completed on $(date)
      - echo Pushing the Docker image...
      - echo Push the latest image to the cluster
      - kubectl apply -f deployment.yml
